[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

board_build.partitions = default.csv
board_build.filesystem = littlefs

monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson
  links2004/WebSockets
  sui77/rc-switch   #For RF module.
  adafruit/RTClib@^2.1.1
  adafruit/DHT sensor library@^1.4.4
  adafruit/Adafruit Unified Sensor@^1.1.14
